### PR TITLE
Windows-Friendly Parallel 

### PR DESCRIPTION
**Pull request by christopherkenny**
This changes from the use of parallel's `mclapply()` to a combo of `foreach` and `doParallel` functions to allow the same parallel code to function on Windows.

`foreach` and `doParallel` are treated as suggests, matching the format of the current usage of `parallel`. 

Additionally, there's a short test added to ensure that the parallel testing is functioning. Depending on your CI setup, you may want to use `testthat::skip_on_ci()` to avoid it failing for lack of those namespaces.

Chris

### CODE REVIEW

**Comment by chris-prener** [comment]
This is great, @christopherkenny! Thanks for the submission. @bransonf - do you want to take a quick look? I like the idea of extending this to Windows machines.

**Comment by bransonf** [comment]
Thanks for the PR @christopherkenny! and thanks for tagging me @chris-prener 

Give me a few days to test this across platforms. I still want to preserve forking over PSOCK for Mac/Linux, as it's far more efficient.

Should have this merged by end of week.

**Comment by bransonf** [comment]
@christopherkenny Thanks again for the PR, now merged to master!

**Comment by chris-prener** [comment]
Yes - thanks @christopherkenny !

**Pull request merged**
