### PR TITLE
Issue7

### PR DESCRIPTION
**Pull request by bransonf**
Proposed fix to #7

### CODE REVIEW

**Comment by chris-prener** [comment]
Looks good! Can you check on the CI failures before we merge the PR, @bransonf?

**Comment by bransonf** [comment]
The failure is due to the placement of `NA`s. For whatever reason, they aren't being properly filtered before attempting to create an sf object. (You can't make an sf object with missing coords)

I've been weighing the original options. We could just wrap separate in `suppressWarnings({})` and be done with it. The function originally passed testing because tidyr didn't produce this warning. If we're worried about losing other information for later debugging, I can wrap it in a `tryCatch()` and return any warning other than the one we anticipate.

As opposed to pushing a more complex, much slower, dependency adding, harder to debug solution.

Weighing the options, I really do think that handling the warning makes more sense than a rewrite.

**Comment by chris-prener** [comment]
Hm, no good choices here it seems. Before we go the `suppressWarnings()` approach, can you see if you can figure out why the `NA` values aren't filtering properly?

**Comment by bransonf** [comment]
Easy fix, but I'm still not totally convinced that handling the warning isn't the better route.

**Pull request closed without merging**
